name: tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        groups:
          - name: fast
            specs: |
              cypress/tests/suite1.spec.js
              cypress/tests/suite2.spec.js
          - name: slow
            specs: cypress/tests/suite3.spec.js
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cypress run (${{ matrix.groups.name }} suites) # Installe aussi les dépendances npm
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          spec: ${{ matrix.groups.specs }}